# Node docker image on which this would be run
image: node:latest

variables:
   npm_config_cache: "$CI_PROJECT_DIR/.npm"
   NODE_ENV: 'test'

cache:
   key:
     files:
        - package.json
   paths:
      - .npm
      - node_modules
      - build

services:
   - mongo

stages:
  - install
  - build
  - test

# Jobs:

install_dependencies:
  stage: install
  script:
    - npm  ci

Build_api:
  stage: build
  script:
    - npm install

test_api:
  stage: test
  script:
    - npm test